import { Container, Theme } from '@radix-ui/themes'
import '@radix-ui/themes/styles.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from './Nav'
import './globals.css'
import './theme-config.css'
import Provider from './auth/Provider'

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
            <body className={inter.variable}>
                <Provider>
                    <Theme appearance='light' accentColor='violet'>
                        <Nav />
                        <main className='p-5'>
                            <Container>{children}</Container>
                        </main>
                    </Theme>
                </Provider>
            </body>
        </html>
    )
}
